### PR TITLE
Add support to pass browser to your app so ex. you can cancel a render

### PR DESCRIPTION
**Pull request by jnx**
Add support for prepare browser so it pass current browser back to app and where you can ex. cancel an ongoing render, close a failed render.

### CODE REVIEW

**Comment by anteOnTheInternets** [comment]
hi @tungs ,
What I and @jnx actually want is to be able to stop an ongoing render. So for us it would be just as fine to expose only a cancel function instead of the whole browser, if that's preferable to you. :)
The latter feels cleaner than having to provide our own browser/launcher to timesnap.

**Comment by dotarmin** [comment]
@tungs, I understand that you are busy... I'm curious about how much time you will spend/work with timesnap. @jnx and @anteOnTheInternets has put time on working with this project and it would be great to get some input and if we should contribute to the project. Worst case scenario we have to continue in our own fork but I hope that we can contribute to this project instead.

Bets regards,
Armin

**Comment by tungs** [comment]
Hi @dotarmin and team, thanks for your interest in this. What somewhat complicates pulls requests like these is that for the next version, I am planning to refactor most of the code to transfer it over to async/await now that puppeteer has migrated to node versions that require it. I'm a little reluctant right now to accept new feature requests/pull requests until I've refactored it.

Currently, other priorities have popped up to supercede this project, but I am planning on taking a look sometime this month at refactoring and pull requests.

For this particular pull request, the async / await convention probably would make it a lot easier to review the request, since it is showing 149 lines deleted and 160 lines added from what I'm guessing is mostly a nested promise. From what I understand, it could also be rewritten in a few lines after https://github.com/tungs/timesnap/blob/d416828bf58f0d8dd7e73642e6fd98d71bd7d2fd/index.js#L121, without adding additional nesting.

In any case, I'm still mulling over (and leaning towards) the idea that adding this configuration option would cause too much bloat, rather than having one function that exposes all of the internal variables (like a `prepare`... function that passes `page`, `browser`, etc.).

**Comment by tungs** [comment]
As it is, this specific feature feels too specific and bloaty. I'd prefer and am planning on adding a generic configuration function that exposes all of the local variables including browser and page for a specific capture session.

You should be able to use `preparePage` to get the browser.

```
timesnap({
  preparePage: page => prepareBrowser(page.browser())
});
```

I could see an issue if the page doesn't load, preparePage doesn't run, and let me know if that's your use case. If that's the case, currently I'd recommend using the aforementioned techniques of using `config.browser` or `config.launcher`.

**Pull request closed without merging**
