### PR TITLE
Add preparePage function for setup of the page

### PR DESCRIPTION
**Pull request by yarres**
* preparePage function added after page.goto(url) in index.js (l. 503 to 509)
* other changes to index.js are only white space due to update to eslint version
* preparePage function allows the user to setup the page before
capturing it
* preparePage function will be called one time only
* Update to README
* Minor package.json (minor bump) and .eslintrc.json updates

### CODE REVIEW

**Comment by tungs** [comment]
Thanks for the contribution @yarres! The implementation looks good, but it should probably be separated from the new eslint version and the reformatting. I think the changes for this PR should only be for the new feature and its relevant documentation.

I'm going to reorganize the code in an upcoming release soon, and I'll revisit eslint settings and overall formatting then. If you'd like to offer some suggestions about the reorganization, see issue #9.

**Comment by yarres** [comment]
Ok, I roll backed the linter and formatting updates.
The diff in readme (except the line on prepare function) are due to my fork having a commit missing from yours.

**Comment by tungs** [comment]
Thanks @yarres! One last thing: could you remove the `package-lock.json` file? It looks like there might be a mismatch in versions. The project should have one though, and I'll add one later today. Thanks!

**Comment by yarres** [comment]
Ok, done :)

**Comment by tungs** [comment]
Awesome! Thanks for your contribution and being accommodating!

**Comment by yarres** [comment]
No problem, thanks for your work on the package!

**Pull request merged**
